name: Playwright E2E

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Install Playwright browsers and system deps
        # --with-deps will install necessary system packages on hosted runners
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=github
